# Generated by Django 4.1.7 on 2023-03-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beansapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
